server.port=8081

# Configuração do EmailJS
emailjs.service-id=${EMAILJS_SERVICE_ID:your_service_id}
emailjs.template-id=${EMAILJS_TEMPLATE_ID:your_template_id}
emailjs.public-key=${EMAILJS_PUBLIC_KEY:your_public_key}
emailjs.private-key=${EMAILJS_PRIVATE_KEY:your_private_key}

spring.mvc.throw-exception-if-no-handler-found=true
