server.port=8081

# Configuração do EmailJS
emailjs.service-id=service_iutk1nl
emailjs.template-id=template_c134zpm
emailjs.public-key=xQAuK45IB8f2X6uG1
emailjs.private-key=wjbr0AY-3JlcXaF4SnzR2

spring.mvc.throw-exception-if-no-handler-found=true
